version: '3'
services:
  api:
    container_name: storyev
    build: 
      context: .
      dockerfile: ./Dockerfile.prod
    ports: 
      - 8000:8000 
    restart: on-failure
    volumes:
      - .:/usr/src/app/
      - ./files:/usr/src/app/files
    depends_on:
      - storyev_postgres
    networks:
      - storyev_network

  storyev_postgres:
    image: postgres:12.1-alpine
    container_name: storyev_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - storyev_network
    
  storyev_pgadmin:
    image: dpage/pgadmin4
    container_name: storyev_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - storyev_postgres
    ports:
      - 5050:80
    networks:
      - storyev_network
    restart: unless-stopped

  # forum-mysql:
  #   image: mysql:5.7
  #   container_name: full_db_mysql
  #   ports: 
  #     - 3306:3306
  #   environment: 
  #     - MYSQL_ROOT_HOST=${DB_HOST} 
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - database_mysql:/var/lib/mysql
  #   networks:
  #     - forum
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_container
  #   depends_on:
  #     - forum-mysql
  #   environment:
  #     - PMA_HOST=mysql # Note the "mysql". Must be the name of the what you used as the mysql service.
  #     - PMA_USER=${DB_USER}
  #     - PMA_PORT=${DB_PORT}
  #     - PMA_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - 9090:80
  #   restart: always
  #   networks:
  #     - forum

volumes:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  storyev_network:
    driver: bridge