version: '3'
services:
  api_test:
    container_name: storyev_test
    build: 
      context: .
      dockerfile: ./Dockerfile.test
    volumes:              
      - .:/usr/src/app
    depends_on:
      - storyev_postgres_test
    networks:
      - storyev_network_test

  storyev_postgres_test:
    image: postgres:12.1-alpine
    container_name: storyev_postgres_test
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - storyev_network_test

volumes:
  database_postgres_test:
    
# Networks to be created to facilitate communication between containers
networks:
  storyev_network_test:
    driver: bridge